### ISSUE TITLE
Where can I find the output?

### ISSUE THREAD

**Issue by RoyceDavison** [taosx/node-keylogger#1]
Hello, could you help me out with my output problem?
What I did:
I clone the repo.
npm install
create test.js and copy all codes under the usage. Only thing I change is replace the old code with 
var Keyboard = require('../');
sudo node test.js on the terminal
Then no response at all, I don`t see any output on the terminal, I keep press key but nothing happen and I can not kill the program with  "CTRL+C".
Thank you for your help!!

**Comment by edgardleal** [comment]
1 - You dont need `sudo`
2 - if tou dont see output, you are monitoring the wront device ( `event1` ) 
3 - try to use `evtest` to list your devices ( `sudo apt-get install evtest` )
